apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaee-cafe
  labels:
    app: javaee-cafe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaee-cafe
  template:
    metadata:
      name: javaee-cafe
      labels:
        app: javaee-cafe
    spec:
      containers:
        - name: javaee-cafe
          image: scbacr1.azurecr.io/javaee-cafe-scb
---
apiVersion: v1
kind: Service
metadata:
  name: javaee-cafe
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: javaee-cafe
